name: S3 primary storage
on:
  push:
    branches:
      - master
      - stable*
  pull_request:

jobs:
  s3-tests-minio:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['7.4'] # phpunit/phpunit[6.5.0, ..., 6.5.14] limits to php 7 only right now for integration tests

    name: php${{ matrix.php-versions }}-minio

    services:
      minio:
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123
        image: bitnami/minio:2021.10.6
        ports:
          - "9000:9000"

    steps:
      - name: Checkout server
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, zip, gd, apcu
          ini-values: "apc.enable_cli=1"

      - name: Set up Nextcloud
        run: |
          mkdir data
          echo "<?php \$CONFIG = ['objectstore' => ['class' => 'OC\\Files\\ObjectStore\\S3', 'arguments' => [ 'bucket' => 'nextcloud', 'key' => 'minio', 'secret' => 'minio123', 'hostname' => 'localhost', 'port' => 9000, 'use_ssl' => false, 'autocreate' => true, 'use_path_style' => true ]]];" > config/s3.config.php
          echo "<?php \$CONFIG = ['memcache.local' => '\\OC\\Memcache\\APCu', 'memcache.distributed' => '\\OC\\Memcache\\APCu'];" > config/apcu.config.php
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
      - name: Integration
        run: |
          cd build/integration
          bash run.sh features/webdav-related.feature
      - name: S3 logs
        if: always()
        run: |
          docker ps -a
          docker logs $(docker ps -aq)
